
services:
  backend:
    build: ./FastAPIProject  # путь к бекенду
    ports:
      - "8000:8000"
    volumes:
      - ./FastAPIProject:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db

  frontend:
    build: ./frontend  # путь к фронту
    ports:
      - "3000:3000"
#    volumes:
#      - ./frontend:/app
    depends_on:
      - backend
